---
defaults: &defaults
  docker:
    - image: circleci/node:10.16

version: 2
jobs:
  build:
    <<: *defaults
    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn

  test:
    <<: *defaults

    working_directory: ~/repo

    steps:
      - run: yarn test
      - run: yarn lint

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - test:
          requires:
            - build