---
defaults: &defaults
  docker:
    - image: circleci/node:10.16

version: 2
jobs:
  build:
    <<: *defaults
    working_directory: ~/repo

    steps:
      - checkout
      - run: ls
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "yarn.lock" }}
            - dependency-cache-{{ checksum "packages/app/yarn.lock" }}
            - dependency-cache-{{ checksum "packages/server/yarn.lock" }}
      - run: yarn
      - run: ls
      - save_cache:
          key: dependency-cache-{{ checksum "./yarn.lock" }}
          paths:
            - node_modules
            - packages/app/node_modules
            - packages/server/node_modules
      - run: yarn lint
      - run: yarn test
      # Workflow not working at the moment
      # - persist_to_workspace:
      #    root: ./
      #    paths:
      #      - ./node_modules
      #      - ./packages/app
      #      - ./paclages/server

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: yarn test
      - run: yarn lint

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      # - test:
      #    requires:
      #      - build