---
defaults: &defaults
  docker:
    - image: circleci/node:10.16

version: 2
jobs:
  build:
    <<: *defaults
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "./yarn.lock" }}
            - dependency-cache-{{ checksum "./packages/app/yarn.lock" }}
            - dependency-cache-{{ checksum "./packages/server/yarn.lock" }}
      - run: yarn
      - run: ls
      - save_cache:
          keys:
            - dependency-cache-{{ checksum "./yarn.lock" }}
            - dependency-cache-{{ checksum "./packages/app/yarn.lock" }}
            - dependency-cache-{{ checksum "./packages/server/yarn.lock" }}
          paths:
            - node_modules
            - packages/app/node_modules
            - packages/server/node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - ./.circleci
            - ./node_modules
            - ./packages/app
            - ./paclages/server

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: ls
      - run: yarn test
      - run: yarn lint

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - test:
          requires:
            - build