---
defaults: &defaults
  docker:
    - image: circleci/node:10.16

version: 2
jobs:
  build:
    <<: *defaults
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys: dependency-cache-{{ checksum "yarn.lock" }}
      - run: yarn
      - run: ls
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/app/node_modules
            - packages/server/node_modules

  test:
    <<: *defaults
    steps:
      - run: ls
      - run: yarn test
      - run: yarn lint

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - test:
          requires:
            - build